src/accounts/urls.py
# Django
from django.urls import path, include
from django.contrib.auth import views as auth_views
# App
from . import views 
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
    #                                            authentication_form=LoginForm), 
    #                                            name='login'),
    path('login/', views.Login, name='login'),
    path('signup/', views.SignUp, name='signup'),
    #path('', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profiles/', views.ProfileListView.as_view(), name='profiles-list'),
    path('profile/<slug:slug>', views.ProfileDetailView.as_view(), name='profile-detail')
]

src/mails/urls.py
# Django
from django.urls import path
# App
from . import views

app_name = 'mails'

urlpatterns = [
    path('mails/', views.MailListView.as_view(), name='mails-list'),
    path('mail/<int:pk>/', views.MailDetailView.as_view(), name="mail-detail"),
    path('mail/delete/<int:pk>/', views.MailDeleteView.as_view(), name="delete")
]

src/playwithus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'),name='index'),
    path('', include(('mails.urls'), namespace='mails')),
    path('', include(('accounts.urls'), namespace='accounts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/_header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Cerrar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Mensajes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profiles-list' %}">Busca y descubre</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#" id="register">Inicia sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" id="login">Regístrate</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <a class="navbar-brand" href="{% url 'index' %}">PLAYWITHUS</a>
        
    </nav>
</header>

src/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PlayWithUs | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    {% block extracss %} {% endblock %}
</head>

<body>
    <div class="container-fluid">
        {% include 'header.html' %}
        <div class="content" id="page-top"></div>
            {% block content %}
            {% endblock %}
      
        {% include 'footer.html' %}
    </div>
    {% block extrascripts %}
    {% endblock extrascripts %}
</body>

src/templates/footer.html
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<div class="bg-custom text-white">
  <footer class="">
    <div class="row mx-auto"> 
      
      <div class="col-12 col-md d-flex flex-column align-items-center justify-content-center pt-2">
        <h3>PLAYWITHUS</h3>
        <p class="mb-3"><small>Todos los derechos reservados &copy</small></p>
      </div>
      
      <div class="col-12 col-md d-md-flex align-items-center justify-content-center">
        <ul class="list-unstyled">
          <li class="pb-2 pt-4">
            <a href="{% url 'index' %}">Inicio</a>
          </li>
          {% if user.is_authenticated %}
            <li class="pb-2">
              <a href="{{ user.get_absolute_url }}">Perfil</a>
            </li>
            <li class="pb-2">
              <a href="{% url 'mails:mails-list' %}">Mensajes</a>
            </li>
            <li class="pb-2">
              <a href="{% url 'accounts:profiles-list' %}">Busca y descubre</a>
            </li>
          {% else %}
            <li class="pb-2">
              <a href="#">Iniciar sesión</a>
            </li>
            <li class="pb-2">
              <a href="#">Regístrate</a>
            </li>
          {% endif %}
        </ul>
      </div>

      <div class="col-12 col-md d-flex justify-content-center align-items-center pt-3 pt-md-0">
          <a href="https://facebook.com/" class="social-round-icon black-round-icon fa-icon" title="">
            <i class="fab fa-facebook" aria-hidden="true"></i>
          </a>
          <a href="https://twitter.com/" class="social-round-icon white-round-icon fa-icon" title="">
            <i class="fab fa-twitter" aria-hidden="true"></i>
          </a>
          <a href="https://www.instagram.com/" class="social-round-icon white-round-icon fa-icon" title="">
            <i class="fab fa-instagram" aria-hidden="true"></i>
          </a>
        
      </div>
    </div>
  </footer>
</div>

src/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-custom fixed-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Cerrar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ request.user.profile.get_absolute_url }}">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mails:mails-list' %}">Mensajes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profiles-list' %}">Busca y descubre</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#myModal">
                            Inicia sesión / Regístrate
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <a class="navbar-brand mr-5" href="{% url 'index' %}">PLAYWITHUS</a>
        
    </nav>
</header>

src/templates/index.html
{% extends "base.html" %}

{% block title %}Inicio{% endblock %}

{% block content %}
  <div class="container">
    {% include "modal.html" %}
    
    <div class="row my-4"> 
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="mx-auto mb-4">
              <img src="../media/index/main-index.jpg" class"img-fluid" alt="main-index" style="height: auto; max-width: 100%;"/>
            </div>
            <div class="main-text">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Saepe nostrum ullam eveniet pariatur voluptates odit, fuga
                atque ea nobis sit soluta odio, adipisci quas excepturi maxime
                quae totam ducimus consectetur?</p>
            <br>
            
        </div>
    </div>
  </div>
{% endblock %}

{% block extrascripts %}
    <script type="text/javascript">
      function login(){
          email = document.getElementById("exampleInputUsername").value;
          password = document.getElementById("exampleInputPassword").value;
          csrfmiddlewaretoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
          $("#errorlogin").html("");
          $.ajax({
              type:"POST",
              url:'/login/',
              data:{
                  'csrfmiddlewaretoken': csrfmiddlewaretoken,
                  'email':email,
                  'password':password,
              },
              success : function(data){
                  console.log(data);
                  if(data['message'] == "Success"){
                      location.reload();
                  }
                  else if(data['message'] == "inactive"){
                      $("#errorlogin").html("Cuenta inactiva actualmente");
                  }
                  else{
                      $("#errorlogin").html("Revise el email y la contraseña");
                  }
              }
          });
      }

      function signup(){
          email = document.getElementById("exampleInputEmail").value;
          fname = document.getElementById("exampleInputFname").value;
          lname = document.getElementById("exampleInputLname").value;
          password1 = document.getElementById("exampleInputPassword1").value;
          password2 = document.getElementById("exampleInputPassword2").value;
          is_group = document.getElementById("exampleCheck1").checked;
          csrfmiddlewaretoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
          $("#erroremail").html("");
          $("#errorpass").html("");
          if(fname == "" || lname == ""){
              $("#errorname").html("Nombre y apellidos son obligatorios");
          }
          else{
          $.ajax({
          type:"POST",
          url:'/signup/',
          data:{
            'csrfmiddlewaretoken': csrfmiddlewaretoken,
            'first_name':fname,
            'last_name':lname,
            'email':email,
            'password1':password1,
            'password2':password2,
            'is_group': is_group
          },
          success : function(data){
              console.log(data['message']);
              if(data['message'] == "Success"){
                  window.location = "/"
              }
              else{
                  if("email" in data['message'])
                      $("#erroremail").html(data['message']['email'][0]);
                  if("password2" in data['message'])
                      $("#errorpass").html(data['message']['password2'][0]);
              }
          }
      })
      }
    }
    </script>
{% endblock %}

src/templates/modal.html
<style type="text/css">
  input{
    max-width:500px;
  }
</style>

<div id="myModal" class="modal fade loginM" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#login">Iniciar sesión</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#signup">Registrarse</a>
            </li>
          </ul>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
             
              
      <div class="modal-body">
        <div class="tab-content">
          <div id="login" class="container tab-pane active">
            <form class='login-form'>
              <div class="form-group">
                <label for="exampleInputUsername">Correo electrónico</label>
                <input type="email" class="form-control" id="exampleInputUsername" aria-describedby="emailHelp" placeholder="Email">
              </div>

              <div class="form-group">
                <label for="exampleInputPassword">Contraseña</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword" placeholder="Password" />
                <div id="errorlogin" style="color:red"></div>
              </div>
              <button type="button" class="btn btn-primary btn-lg btn-block login-btn" 
                style="max-width:500px" onclick="login()">Iniciar sesión</button>
            </form>
          </div>

          
          <div id="signup" class="container tab-pane">
            <form class='login-form'>
                          
              <div class="form-group">
                <div id="errorname" style="color:red">
                </div>
                <label for="exampleInputFname">Nombre</label>
                <input type="text" class="form-control" id="exampleInputFname" aria-describedby="emailHelp" 
                  placeholder="Ingrese nombre">
              </div>

              <div class="form-group">
                <label for="exampleInputLname">Apellidos</label>
                <input type="text" class="form-control" id="exampleInputLname" aria-describedby="emailHelp" 
                  placeholder="Ingrese apellidos">
              </div>

              <div class="form-group">
              <div id="erroremail" style="color:red">
              </div>
                <label for="exampleInputEmail">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" 
                  placeholder="Ingrese email">
              </div>
                                  
              <div class="form-group">
              <div id="errorpass" style="color:red">
              </div>
                <label for="exampleInputPassword1">Contraseña</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingrese contraseña" />
              </div>

              <div class="form-group">
                <label for="exampleInputPassword2">Confirmar contraseña</label>
                <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Repite contraseña" />
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1" name="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Represento a un grupo musical</label>
              </div>
              <button type="button"  class="btn btn-primary btn-lg btn-block login-btn mb-2 mt-2" style="max-width:500px" onclick="signup()">Registrarse</button>
              {% csrf_token %}
            </form>
          </div>
         

        </div>
      </div>
    </div>
  </div>
</div>