src/accounts/urls.py
# Django
from django.urls import path, include
from django.contrib.auth import views as auth_views
# App
from . import views 
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    #path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
    #                                            authentication_form=LoginForm), 
    #                                            name='login'),
    path('login/', views.Login, name='login'),
    path('signup/', views.SignUp, name='signup'),
    #path('', include('django.contrib.auth.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profiles/', views.ProfileListView.as_view(), name='profiles-list'),
    path('profile/<slug:slug>', views.ProfileDetailView.as_view(), name='profile-detail')
]

src/mails/urls.py
# Django
from django.urls import path
# App
from . import views

app_name = 'mails'

urlpatterns = [
    path('mails/', views.MailListView.as_view(), name='mails-list'),
    path('mail/<int:pk>/', views.MailDetailView.as_view(), name="mail-detail"),
    path('mail/delete/<int:pk>/', views.MailDeleteView.as_view(), name="delete")
]

src/playwithus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'),name='index'),
    path('', include(('mails.urls'), namespace='mails')),
    path('', include(('accounts.urls'), namespace='accounts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/experiences/models.py
from django.db import models
from accounts.models import Profile

class Experience(models.Model):

    TYPE = (
        ('CURSO', 'Curso'),
        ('PROFESIONAL', 'Profesional'),
        ('ARTISTICA', 'Artistica'),
        ('OTRO', 'Otro')
    )

    DURATION = (
        ('0-3', '0 a 3 meses'),
        ('3-6', '3 a 6 meses'),
        ('6-1A', '6 meses a 1 año'),
        ('1A-2A', '1 año a 2 años'),
        ('2A-4A', '2 años a 4 años'),
        ('4A-6A', '4 años a 6 años'),
        ('6+', '6 años o mas')
    )

    center = models.CharField(max_length=200, null=True, blank=True)
    group = models.CharField(max_length=200, null=True, blank=True)
    type = models.CharField(max_length=50, choices=TYPE)
    duration = models.CharField(max_length=50, choices=DURATION)
    observations = models.CharField(max_length=255, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='experiences')

    class Meta:

        ordering = ('-updated',)

src/instruments/models.py
from django.db import models
from accounts.models import Profile

class Instrument(models.Model):

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200, null=True, blank=True)
    instrumentalists = models.ManyToManyField(Profile, through='InstrumentUser', related_name='instruments',)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.name    

class InstrumentUser(models.Model):

    LEVELS = (
        ('PRINCIPIANTE', 'Principiante'),
        ('ELEMENTAL', 'Grado elemental'),
        ('MEDIO', 'Grado medio'),
        ('SUPERIOR', 'Grado superior'),
        ('ELEMENTAL-NO', 'Grado elemental (sin titulación)'),
        ('MEDIO-NO', 'Grado medio (sin titulación)'),
        ('SUPERIOR-NO', 'Grado superior (sin titulación)'),
        ('MASTER', 'Máster')
    )

    profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING,)
    instrument = models.ForeignKey(Instrument,on_delete=models.DO_NOTHING,)
    level = models.CharField(max_length=50, choices=LEVELS)

    def __str__(self):
        return f"{self.profile.displayname} - {self.instrument.name} | {self.level}"

src/templates/profiles/profile_detail.html
{% extends 'base.html' %}
{% block title %}Perfil{% endblock %}
{% load static %}
{% block extracss %}
    <link rel="stylesheet" href="{% static 'css/profile_detail.css' %}">
{% endblock %}
{% block content %}
      <div class="container">
        <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{ profile.photo.url}}" alt="avatar" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ profile.displayname }}</h4>
                      <p class="text-secondary mb-3">
                      {% if profile.location %}
                      {{ profile.location }}</p>
                      {% else %}
                      Ciudad sin definir</p>
                      {% endif %}                     
                      <form action="{% comment %} {% url 'mails:create' pk=user.id %} {% endcomment %}" method="post">
                          {% csrf_token %}
                          <button class="btn btn-circle bg-custom text-white">
                              <i class="fa fa-envelope-open"></i>
                          </button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Nombre completo</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.user.first_name }} {{ profile.user.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Ciudad</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {% if profile.location %}
                        {{ profile.location }}
                      {% endif %}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Fecha de nacimiento</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {% if profile.user.date_of_birth %}
                        {{ profile.user.date_of_birth }}
                      {% endif %}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Bio</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {% if profile.bio %}
                        {{ profile.bio}}
                      {% endif %}
                    </div>
                  </div>
                  <hr>
                  {% if profile.user.email == request.user.email %}
                    <div class="row">
                      <div class="col-sm-12 edit-icon">
                        <button class="btn btn-circle bg-custom text-white">
                          <i class="fa fa-edit"></i>
                        </button>
                      </div>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <div class="row gutters-sm">
            <div class="col-sm-6 mb-3">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row">
                      <div class="col-sm-10">
                        <h6 class="d-flex align-items-center mb-3">Instrumentos</h6>
                      </div>
                      {% if profile.user.email == request.user.email %}
                        <div class="col-sm-2 mb-2">
                          <button class="btn btn-circle btn-success text-white">
                            <i class="fa fa-plus"></i>
                          </button>
                        </div>
                      {% endif %}
                  </div>
                  {% for object in profile.instrumentuser_set.all%}
                    <div class="">
                      <p class="d-block">{{ object.instrument.name }}</p>
                      <small>{{ object.get_level_display }}</small>
                      <hr/>
                    </div>  
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="col-sm-6 mb-3">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row">
                      <div class="col-sm-10">
                        <h6 class="d-flex align-items-center mb-3">Experiencia</h6>
                      </div>
                      {% if profile.user.email == request.user.email %}
                        <div class="col-sm-2 mb-2">
                          <button class="btn btn-circle btn-success text-white">
                            <i class="fa fa-plus"></i>
                          </button>
                        </div>
                      {% endif %}
                  </div>
                  {% for object in profile.experiences.all %}
                    <ul class="list-group">
                    
                        {% if object.center %}
                        <li class="list-group-item"><b>Centro</b>      {{ object.center }}</li>
                        {% endif %}
                        {% if object.group %}
                            <li class="list-group-item"><b>Grupo</b>      {{ object.group }}</li>
                        {% endif %}
                        {% if object.type %}
                            <li class="list-group-item"><b>Tipo:</b>      {{ object.get_type_display }}</li>
                        {% endif %}
                        {% if object.duration %}
                            <li class="list-group-item"><b>Duración</b>      {{ object.get_duration_display }}</li>
                        {% endif %}
                        {% if object.observations %}
                            <li class="list-group-item"><b>Observaciones</b>      {{ object.observations }}</li>
                        {% endif %}
                    </ul>
                    <hr>
                  {% endfor %}
                  
                </div>
              </div>
            </div>
          </div>
          {% for comment in profile.comments_received.all%}
            <div class="row gutters-sm">
              <div class="col-sm-12 mb-3">
                <div class="card h-100">
                  <div class="card-body"> 
                    <div class="media">
                      <div class="img-fluid">
                        <img class="mr-3" style="width:50px;height:50px;" src="{{ comment.creator.photo.url }}" alt="avatar">
                      </div>
                      <div class="media-body">
                        <h5 class="mt-0">{{ comment.creator.displayname }}</h5>
                        <p>{{ comment.body }}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div> 
          {% endfor %}
        </div>
    </div>
  
{% endblock %}

src/templates/profiles/profile_list.html
{% extends "base.html" %}
{% block title %}Perfiles{% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block extracss %}
    <link rel="stylesheet" href="{% static 'css/profile_detail.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4>Opciones de filtrado</h4>
                <form method="get">
                    <div class="form-group row no-gutters">
                        <h6>Nombre</h6>
                        <div class="col-10">
                            {% render_field filter.form.displayname class="form-control" %}
                        </div>
                        <div class="col-2">
                            <button type="submit" href="{% url 'accounts:profiles-list' %}" class="btn btn-circle bg-custom text-white">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-12">
                            {% render_field filter.form.user__is_group class="form-control" %}
                        </div>
                    </div>
                    
                    <div class="form-group row no-gutters">
                        <h6>Instrumento</h6>
                        <div class="col-10">
                            {% render_field filter.form.instruments__name class="form-control" %}
                        </div>
                        <div class="col-2">
                            <button type="submit" class="btn btn-circle bg-custom text-white">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            
            <div class="col-md-9 col-md-3">
                <div class="card">
                    <div class="card-body">
                        {% for profile in profile_list %}
                        <section class="search-result-item">
                            <div class="row">
                                <div class="col-lg-6">
                                    <a class="image-link" href="{{ profile.get_absolute_url }}">
                                        <img class="image" style="width:300px;height:300px;"src="{{ profile.photo.url }}">
                                    </a>
                                </div>
                                <div class="col-lg-6 pt-2">
                                    {% for object in profile.instrumentuser_set.all%}
                                        <div class="">
                                        <p class="d-block">{{ object.instrument.name }}</p>
                                        <small>{{ object.get_level_display }}</small>
                                        <hr/>
                                        </div>  
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="search-result-item-body">
                                <div class="row">
                                    <div class="col-sm-9">
                                        <h4 class="search-result-item-heading mt-2"><a href="{{ profile.get_absolute_url }}">{{ profile.displayname }}</a></h4>
                                        {% if profile.location %}
                                            <p class="info">{{ profile.location }}</p>
                                        {% else %}
                                            <p class="info">Ciudad</p>
                                        {% endif %}
                                        {% if profile.bio %}
                                            <p class="description">{{ profile.bio }}</p>
                                        {% else %}
                                            <br><br>
                                        {% endif %}
                                    
                                    </div>
                                    <div class="col-sm-3 text-align-center">
                                        <a class="btn btn-primary bg-custom btn-sm" href="{{ profile.get_absolute_url }}">Ver perfil</a>
                                    </div>
                                </div>
                            </div>
                        </section>
                        {% endfor %}
                        <div class="row">
                            <nav>
                                {% if is_paginated %}
                                    <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                    <i class="fa fa-arrow-left" aria-hidden="true"></i>
                                                </a>
                                            </li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            <li class="page-item" {% if page_obj.number == i %} class="active" {% endif %}>
                                                <a class="page-link" href="?page={{i}}">{{ i }}</a>
                                            </li>
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                    <i class="fa fa-arrow-right" aria-hidden="true"></i>
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}